@GameOfLife.Api_HostAddress = http://localhost:5276

# GET {{GameOfLife.Api_HostAddress}}/weatherforecast/
# Accept: application/json


GET {{GameOfLife.Api_HostAddress}}/game/GetOriginalBoardState/smallspacefiller.cells.json
Accept: application/json


###
